M48
; DRILL file {KiCad 9.0.6} date 2026-01-20T12:08:29-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-20T12:08:29-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C4.300
%
G90
G05
T1
X11.61Y5.315
X17.39Y5.315
T2
X8.2Y48.3
X48.0Y71.5
X90.0Y71.5
X122.5Y11.0
M30
