M48
; DRILL file KiCad 10.0.1 date 2026-07-06T15:16:56
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2026-07-06T15:16:56+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.1457
%
G90
G05
T1
X1.752Y0.6811
T2
X0.2953Y1.1909
X0.2953Y0.187
X5.2165Y1.1909
X5.2165Y0.187
M30
