// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------- //
// pio_spi_mode1 //
// ------------- //

#define pio_spi_mode1_wrap_target 0
#define pio_spi_mode1_wrap 3

static const uint16_t pio_spi_mode1_program_instructions[] = {
            //     .wrap_target
    0x80a0, //  0: pull   block           side 0     
    0xe037, //  1: set    x, 23           side 0     
    0x7001, //  2: out    pins, 1         side 1     
    0x0042, //  3: jmp    x--, 2          side 0     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pio_spi_mode1_program = {
    .instructions = pio_spi_mode1_program_instructions,
    .length = 4,
    .origin = -1,
};

static inline pio_sm_config pio_spi_mode1_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pio_spi_mode1_wrap_target, offset + pio_spi_mode1_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}

#include "hardware/clocks.h"
#include "hardware/gpio.h"
#define PIO_SPI_ADC_BAUD_HZ  10000000u   /* 10 MHz */
#define PIO_SPI_DAC_BAUD_HZ  30000000u   /* 30 MHz */

/**
 * Initialise pio_spi_mode1 on the given SM.
 * mosi / sck are ABSOLUTE GPIO numbers (correct for RP2350 pio_set_gpio_base).
 */
static inline void pio_spi_mode1_init(
        PIO pio, uint sm, uint offset,
        uint mosi, uint sck)
{
    pio_sm_config c = pio_spi_mode1_program_get_default_config(offset);
    sm_config_set_out_pins    (&c, mosi, 1);
    sm_config_set_sideset_pins(&c, sck);
    /* MSB-first, no autopull; explicit pull in the program */
    sm_config_set_out_shift(&c, /*shift_dir=*/false, /*autopull=*/false, 8);
    /* 2 PIO cycles per SCK period */
    float div = (float)clock_get_hz(clk_sys) / (2.f * (float)PIO_SPI_DAC_BAUD_HZ);
    sm_config_set_clkdiv(&c, div);
    pio_gpio_init(pio, mosi);
    pio_gpio_init(pio, sck);
    pio_sm_set_consecutive_pindirs(pio, sm, mosi, 1, true);
    pio_sm_set_consecutive_pindirs(pio, sm, sck,  1, true);
    /* Ensure SCK idles low between frames */
    gpio_set_pulls(sck, /*up=*/false, /*down=*/true);
    pio_sm_init(pio, sm, offset, &c);
    /* Caller enables the SM via pio_sm_set_enabled() */
}

#endif

// ------------- //
// pio_spi_mode2 //
// ------------- //

#define pio_spi_mode2_wrap_target 0
#define pio_spi_mode2_wrap 7

static const uint16_t pio_spi_mode2_program_instructions[] = {
            //     .wrap_target
    0x90a0, //  0: pull   block           side 1     
    0xf02e, //  1: set    x, 14           side 1     
    0x7001, //  2: out    pins, 1         side 1     
    0x4001, //  3: in     pins, 1         side 0     
    0x7001, //  4: out    pins, 1         side 1     
    0x1043, //  5: jmp    x--, 3          side 1     
    0x4001, //  6: in     pins, 1         side 0     
    0x9020, //  7: push   block           side 1     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pio_spi_mode2_program = {
    .instructions = pio_spi_mode2_program_instructions,
    .length = 8,
    .origin = -1,
};

static inline pio_sm_config pio_spi_mode2_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pio_spi_mode2_wrap_target, offset + pio_spi_mode2_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}

/**
 * Initialise pio_spi_mode2 on the given SM.
 * miso / mosi / sck are ABSOLUTE GPIO numbers.
 */
static inline void pio_spi_mode2_init(
        PIO pio, uint sm, uint offset,
        uint miso, uint mosi, uint sck)
{
    pio_sm_config c = pio_spi_mode2_program_get_default_config(offset);
    sm_config_set_in_pins     (&c, miso);
    sm_config_set_out_pins    (&c, mosi, 1);
    sm_config_set_sideset_pins(&c, sck);
    /* MSB-first, no autopush / autopull; explicit pull/push in the program */
    sm_config_set_in_shift (&c, /*shift_dir=*/false, /*autopush=*/false, 16);
    sm_config_set_out_shift(&c, /*shift_dir=*/false, /*autopull=*/false, 16);
    float div = (float)clock_get_hz(clk_sys) / (2.f * (float)PIO_SPI_ADC_BAUD_HZ);
    sm_config_set_clkdiv(&c, div);
    pio_gpio_init(pio, miso);
    pio_gpio_init(pio, mosi);
    pio_gpio_init(pio, sck);
    pio_sm_set_consecutive_pindirs(pio, sm, miso, 1, false); /* input  */
    pio_sm_set_consecutive_pindirs(pio, sm, mosi, 1, true);  /* output */
    pio_sm_set_consecutive_pindirs(pio, sm, sck,  1, true);  /* output */
    /* Ensure SCK idles high between frames */
    gpio_set_pulls(sck, /*up=*/true, /*down=*/false);
    pio_sm_init(pio, sm, offset, &c);
    /* Caller enables the SM via pio_sm_set_enabled() */
}

#endif
